server:
  port: ${ATTENDANCE_SERVICE_PORT:9002}
  forward-headers-strategy: framework

gateway:
  url: ${GATEWAY_URL:http://localhost:9000}

spring:
  application:
    name: attendance-service
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-rapid-thunder-aio4c6y7-pooler.c-4.us-east-1.aws.neon.tech/attendance_service_db?sslmode=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_0NfvBHSXDru8}
  jpa:
    hibernate:
      ddl-auto: update
  # LoadBalancer + Eureka: Feign @FeignClient(name = "hr-service") gọi trực tiếp instance HR (không qua gateway)
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka}:${EUREKA_PASSWORD:eureka123}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

springdoc:
  api-docs:
    path: /api/attendance/v3/api-docs
  servers:
    - url: http://localhost:9000
      description: API Gateway
