server:
  port: 8002

spring:
  application:
    name: attendance-service
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://ep-rapid-thunder-aio4c6y7-pooler.c-4.us-east-1.aws.neon.tech/attendance_service_db?sslmode=require
    username: neondb_owner
    password: npg_0NfvBHSXDru8
  jpa:
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

springdoc:
  api-docs:
    path: /api/attendance/v3/api-docs
