spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-service
          uri: ${gateway.targets.hr}
          predicates:
            - Path=/api/hr/**

        - id: attendance-service
          uri: ${gateway.targets.attendance}
          predicates:
            - Path=/api/attendance/**

        - id: request-service
          uri: ${gateway.targets.request}
          predicates:
            - Path=/api/request/**

        - id: system-service
          uri: ${gateway.targets.system}
          predicates:
            - Path=/api/system/**

server:
  port: 8000

gateway:
  targets:
    hr: http://localhost:8001
    attendance: http://localhost:8002
    request: http://localhost:8003
    system: http://localhost:8004

eureka:
  client:
    enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    urls:
      - name: 1. Nhân sự (HR)
        url: /api/hr/v3/api-docs
      - name: 2. Chấm công (Attendance)
        url: /api/attendance/v3/api-docs
      - name: 3. Đơn từ (Request)
        url: /api/request/v3/api-docs
      - name: 4. Hệ thống (System)
        url: /api/system/v3/api-docs