server:
  port: 8001 

spring:
  application:
    name: hr-service
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://ep-rapid-thunder-aio4c6y7-pooler.c-4.us-east-1.aws.neon.tech/hr_service_db?sslmode=require
    username: neondb_owner
    password: npg_0NfvBHSXDru8
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

springdoc:
  api-docs:
    path: /api/hr/v3/api-docs
